import { useTheme } from '../lib/theme-context'

/*
 * The one drawing of what the system does.
 *
 * The two SVGs are generated by `scripts/render_pipeline_diagram.py` — the
 * geometry is authored once there and only the palette differs, so the light
 * and dark versions cannot drift apart, and the README and architecture doc
 * embed the same files rather than a second drawing of the same idea. Edit the
 * script, not the SVGs.
 *
 * Referenced by `src` rather than inlined: the file is ~14 kB of markup that
 * belongs in a cacheable asset, not in the JS bundle every visitor parses.
 *
 * It scrolls inside its own container below `lg`. Scaled to fit a 390px phone
 * the labels land at about 3px, which is a picture of a diagram rather than a
 * diagram — a reader who wants the detail can pan to it, and the four steps
 * below say the same thing in words for one who does not.
 */
export default function PipelineDiagram() {
  const { theme } = useTheme()
  const src = theme === 'dark' ? '/img/pipeline-dark.svg' : '/img/pipeline-light.svg'

  return (
    <figure className="m-0">
      <div className="-mx-4 overflow-x-auto px-4 sm:mx-0 sm:px-0">
        <img
          src={src}
          width={1180}
          height={562}
          alt="How the agent works, in four stages. One: ingest — prices,
               filings, earnings history, news sentiment, macro rates and
               options flow, each fact carrying a source and a date. Two: score
               — six weighted factors resolved into one number and shown with
               their contributions. Three: confirm — a changed verdict must be
               agreed by three fresh evaluations, serve a minimum dwell and
               clear a hysteresis band, except a sell, which is exempt from
               every delay. Four: act — position cap, daily-loss switch,
               cash reserve and a refusal to open unbracketed, then an order
               proposed to you or placed unattended. Deep research runs
               alongside on four scoped agents and may veto a buy, but never
               creates one and never reaches an exit. Every outcome returns to
               the record as win rate, calibration and profit net of
               commission."
          className="h-auto w-full min-w-[880px] max-w-none lg:min-w-0"
          loading="lazy"
          decoding="async"
        />
      </div>
      <figcaption className="mt-4 text-[12px] text-[var(--color-fg-muted)] lg:hidden">
        Scroll to follow the cycle, or read the four steps below.
      </figcaption>
    </figure>
  )
}
