"""
Auth helpers — password hashing, JWT creation/validation, account shape.

**The token carries no tier and no capabilities**, and that is deliberate.
`get_current_user` loads the whole user document on every request anyway, so a
claim would save no query — and it would be stale for the token's entire
lifetime, which means an admin downgrade would take effect whenever the user
next happened to sign in rather than on their next request. For a control whose
whole purpose is to stop a spend now, that is the wrong direction. Changing this
payload also changes the login path, which is the one thing on this API that
must not break.
"""
import secrets
import string
from datetime import datetime, timedelta, timezone
from typing import Optional

from jose import JWTError, jwt
from passlib.context import CryptContext

from app.config import get_settings
from app.models.user import AccessTier

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

#: Minimum length everywhere a password is set — the admin form, the reset
#: page, and a user changing their own. Twelve rather than eight because the
#: first one an account gets is generated by the operator and travels by email,
#: so it lives in at least two inboxes before anybody changes it.
MIN_PASSWORD_LENGTH = 12


def hash_password(password: str) -> str:
    return pwd_context.hash(password)


def verify_password(plain: str, hashed: str) -> bool:
    return pwd_context.verify(plain, hashed)


def create_access_token(user_id: str, email: str) -> str:
    """
    Mint a session token.

    `iat` is what lets a password change end every *other* session. Without it
    a reset would rotate the credential while leaving any already-issued token
    working for up to `jwt_expire_hours` — which is most of the point of
    resetting a password somebody else may know. `get_current_user` compares it
    against `password_changed_at` on the document.

    Still no tier and no capabilities here: see the module docstring.
    """
    settings = get_settings()
    now = datetime.now(tz=timezone.utc)
    expire = now + timedelta(hours=settings.jwt_expire_hours)
    payload = {"sub": user_id, "email": email, "iat": now, "exp": expire}
    return jwt.encode(payload, settings.jwt_secret_key, algorithm=settings.jwt_algorithm)


def token_predates_password_change(payload: dict, user: dict) -> bool:
    """
    Whether this token was issued before the account's password last changed.

    Fails **closed** on a token with no `iat` when a change has been recorded:
    those are tokens minted before this field existed, and the only accounts
    carrying `password_changed_at` are ones somebody has deliberately reset —
    exactly the case where an old session must not survive. An account that has
    never had a password change is unaffected either way, which is what stops
    this signing everybody out on deploy.
    """
    changed_at = user.get("password_changed_at")
    if not isinstance(changed_at, datetime):
        return False
    if changed_at.tzinfo is None:
        changed_at = changed_at.replace(tzinfo=timezone.utc)

    issued_raw = payload.get("iat")
    if issued_raw is None:
        return True
    try:
        issued = datetime.fromtimestamp(float(issued_raw), tz=timezone.utc)
    except (TypeError, ValueError, OSError):
        return True

    # One second of slack. `iat` is encoded to whole seconds while
    # `password_changed_at` keeps microseconds, so the token minted alongside a
    # change — which is how `PUT /auth/password` keeps the caller signed in —
    # would otherwise read as older than the change it accompanies.
    return issued < changed_at - timedelta(seconds=1)


def decode_token(token: str) -> Optional[dict]:
    settings = get_settings()
    try:
        return jwt.decode(token, settings.jwt_secret_key, algorithms=[settings.jwt_algorithm])
    except JWTError:
        return None


#: Unambiguous in a monospaced font and in a phone's mail app. No l/1/I/O/0 —
#: a generated password is read off a screen and typed by hand at least once.
_PASSWORD_ALPHABET = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def generate_password(length: int = 16) -> str:
    """A password for an account the operator is about to email credentials for."""
    return "".join(secrets.choice(_PASSWORD_ALPHABET) for _ in range(length))


def new_user_document(
    *,
    email: str,
    password: str,
    display_name: str = "",
    access_tier: AccessTier = AccessTier.BASIC,
    watchlist_cap: Optional[int] = None,
    research_daily_allowed: bool = False,
) -> dict:
    """
    The shape of a freshly provisioned account, in one place.

    Two things create accounts — `scripts/create_user.py` and
    `POST /admin/users` — and they must not drift. A field added by one and
    missed by the other is a document that reads as something nobody intended:
    a missing `access_tier` resolves to BASIC, so the drift would show up as an
    account that silently has less access than the operator granted.

    `watchlist_cap` is omitted entirely when None rather than written as null,
    so the tier default applies *and keeps applying* if that default is ever
    retuned. A stored copy of today's default would freeze it per account.

    Defaults to BASIC. The operator's own account is created with an explicit
    tier; everything else starts at the smallest thing that is useful.
    """
    doc: dict = {
        "email": email,
        "password_hash": hash_password(password),
        "display_name": display_name or email.split("@")[0],
        "created_at": datetime.now(tz=timezone.utc),
        # None until the user sets their own; the global defaults apply.
        "scoring_weights": None,
        "access_tier": AccessTier(access_tier).value,
        "research_daily_allowed": bool(research_daily_allowed),
    }
    if watchlist_cap is not None:
        doc["watchlist_cap"] = max(0, int(watchlist_cap))
    return doc


def password_update(new_password: str) -> dict:
    """
    The `$set` document for a password change. Every path uses this one.

    It exists so that no route can rotate a password and forget
    `password_changed_at`. That omission would not fail anything visibly — the
    new password would work — it would just silently leave every previously
    issued token valid, which is the failure a reset is supposed to prevent.
    """
    return {
        "password_hash": hash_password(new_password),
        "password_changed_at": datetime.now(tz=timezone.utc),
    }
