"""
Trade Rationale
───────────────
The few words a trade record carries to justify itself: why this position was
opened, and why it was closed.

Every order this system places already had numbers behind it — six weighted
sub-scores, a threshold, an analyst conviction — and the trade record kept none
of them. A row that says `BUY 57 HXL @ 41.20` asks the reader to trust a
decision whose reasoning was thrown away at the moment it was made, which is
the opposite of what an audit trail is for.

Two rules hold the wording honest, and both are the same rule the rest of this
codebase already follows:

**Nothing here is generated by a model.** These are pure functions over the
feature document and the effective weights. A justification written by an LLM
would be a plausible sentence about a decision it did not make; this one is the
arithmetic that actually produced the score, in words.

**A factor is named only when the weights genuinely produced the score.**
`scoring.explain_score` sets `attributable: False` on the XGBoost path because a
weighted decomposition of a model output is a fabrication — so this module says
so in as many words rather than naming drivers it cannot stand behind. Same for
a missing feature document: the score sentence is written, the drivers clause is
simply absent. An empty clause is a smaller failure than an invented one.
"""
from app.services.scoring import ALT_FACTOR, FACTORS, effective_weights
from app.services.signal_generator import BUY_THRESHOLD, SELL_THRESHOLD

__all__ = ["entry_rationale", "exit_rationale", "score_drivers"]

#: How each factor is named when it pushed the score up, and when it dragged it
#: down. Written as what a trader would say out loud, not as the feature key —
#: "sentiment_score = 0.81" is data, "positive news sentiment" is a reason.
_FACTOR_WORDS: dict[str, tuple[str, str]] = {
    "technical":        ("strong technicals", "weak technicals"),
    "fundamental":      ("solid fundamentals", "weak fundamentals"),
    "sentiment":        ("positive news sentiment", "negative news sentiment"),
    "macro":            ("a supportive macro backdrop", "an adverse macro backdrop"),
    "volatility":       ("steady volatility", "elevated volatility"),
    "catalyst":         ("a near-term catalyst", "no near-term catalyst"),
    "alternative_data": ("supportive options and insider flow",
                         "weak options and insider flow"),
}

#: The smallest move a factor must make before it is worth naming, measured in
#: composite points (0–1 scale, so 0.02 is two points of the 0–100 score the
#: user sees). Below this a factor is arithmetically present and rhetorically
#: noise: naming a 0.3-point nudge alongside a 12-point one misrepresents which
#: one decided the trade.
MATERIAL_LIFT = 0.02

#: How many supporting factors to name. Two is the point at which a reason stops
#: being a headline and starts being a list — and a list of six is what the
#: factor breakdown panel is for.
_MAX_DRIVERS = 2


def score_drivers(
    feat: dict | None, user_weights: dict | None = None
) -> tuple[list[str], list[str], bool]:
    """
    Which factors moved this score, and which way.

    Returns `(supporting, opposing, attributable)` — phrases ready to drop into
    a sentence, strongest first, and whether attribution was possible at all.

    A factor's weight is not its influence. A 0.35-weighted technical score
    sitting at exactly 0.50 contributed 0.175 to the composite and *decided
    nothing*: it moved the score neither up nor down. So factors are ranked on
    lift away from the neutral 0.5 baseline — `weight × (score − 0.5)` — which
    is the number that answers "why is this 0.82 and not 0.50". Ranking on raw
    contribution instead would put the heaviest weight at the top of every
    reason ever written, regardless of what the company did.

    Alternative data is already an additive modifier centred on 0.5, so it
    enters this comparison on exactly the same footing as the six base factors.
    """
    if not feat:
        return [], [], False

    method = feat.get("scoring_method")
    if method == "xgboost":
        # The weights did not produce this number, so no decomposition of it is
        # true. Callers must say that rather than name a driver.
        return [], [], False

    weights = effective_weights(user_weights)

    lifts: list[tuple[float, str]] = []
    for key, feature_key, _label in FACTORS:
        score = float(feat.get(feature_key, 0.5) or 0.5)
        lifts.append((float(weights.get(key, 0.0)) * (score - 0.5), key))

    alt_key, alt_feature, _alt_label = ALT_FACTOR
    alt_score = float(feat.get(alt_feature, 0.5) or 0.5)
    lifts.append((float(weights.get(alt_key, 0.0)) * (alt_score - 0.5), alt_key))

    supporting = [
        _FACTOR_WORDS[key][0]
        for lift, key in sorted(lifts, reverse=True)
        if lift >= MATERIAL_LIFT and key in _FACTOR_WORDS
    ]
    opposing = [
        _FACTOR_WORDS[key][1]
        for lift, key in sorted(lifts)
        if lift <= -MATERIAL_LIFT and key in _FACTOR_WORDS
    ]
    return supporting, opposing, True


def _join(phrases: list[str]) -> str:
    """`a`, `a and b` — never an Oxford list, since at most two are named."""
    return " and ".join(phrases)


def _pct(value: float) -> int:
    return round(value * 100)


def _drivers_clause(
    feat: dict | None,
    user_weights: dict | None,
    *,
    favourable: bool,
) -> str:
    """
    The `— strong technicals and positive news sentiment, despite …` half.

    `favourable` picks which side leads: a buy is argued from what supported it
    and concedes the drag, a sell from what worked against it. The concession is
    the part that earns the trust — a reason that only ever lists agreement
    reads as marketing, and the trader already knows no setup is unanimous.
    """
    supporting, opposing, attributable = score_drivers(feat, user_weights)
    if not attributable:
        if feat and feat.get("scoring_method") == "xgboost":
            return " — from the ML model, so no factor attribution"
        return ""

    lead, concede = (supporting, opposing) if favourable else (opposing, supporting)
    if not lead:
        # Nothing cleared MATERIAL_LIFT in the deciding direction. Saying so is
        # a real fact about the setup: the score came from the middle of every
        # factor rather than from one that stood out.
        return " — no single factor stood out"

    clause = f" — {_join(lead[:_MAX_DRIVERS])}"
    if concede:
        clause += f", despite {concede[0]}"
    return clause


def entry_rationale(
    *,
    signal_score: float | None,
    feat: dict | None = None,
    user_weights: dict | None = None,
    conviction: str | None = None,
    source: str = "BUY",
    is_add: bool = False,
) -> str:
    """
    Why this position is being opened, in one line a person can check.

    `source` is the `signal_type` the trade is recorded under: "BUY" for the
    agent acting on its own signal, "MANUAL" for an order a person placed,
    "PROPOSAL_APPROVED" for one the agent proposed and a person accepted. The
    three are kept apart here for the same reason performance keeps them apart:
    a human's order is not evidence about the engine, and a sentence claiming
    the score bought it would be false.

    Never raises and never returns an empty string — a record with a blank
    justification is worse than one with a modest one.
    """
    if source == "MANUAL":
        # No drivers clause, and deliberately. The person chose the ticker and
        # the moment; naming the factors the engine happens to like right now
        # would read as the engine endorsing an order it had no part in, which
        # is the same conflation `/performance/trades` keeps three buckets to
        # avoid. The human is the whole reason, so the human is the whole
        # sentence.
        return "Your order, placed from the ticket."
    if source == "PROPOSAL_APPROVED":
        head = "You approved the agent's proposal"
    elif signal_score is None:
        head = "Entry taken"
    else:
        head = (
            f"Scored {_pct(signal_score)}/100 against the "
            f"{_pct(BUY_THRESHOLD)} a buy needs"
        )

    text = head + _drivers_clause(feat, user_weights, favourable=True)

    if conviction:
        # "analyst conviction", never a bare "conviction": research carries a
        # 0–100 number under that word and the two are not the same measure.
        text += f". Analyst conviction {conviction.upper()}"

    if is_add:
        # An add is a different decision from an entry — it is taken against a
        # position already held, at a price below its blended cost — and a
        # record that reads identically to the opening buy hides that. A colon
        # rather than a dash: the drivers clause has already spent one.
        text = f"Added to the position: {text[0].lower()}{text[1:]}"

    return text.rstrip(". ") + "."


#: The base sentence for each way a position can be closed.
#:
#: `execute_exit` has always known this and always threw it away: the trigger
#: reached a log line and a push notification, and the trade document kept
#: nothing. Reconciliation would later stamp `bracket_or_manual` on anything it
#: found flat, so a stop firing and the agent acting on its own SELL signal
#: were indistinguishable in the one place a reader actually looks. A closed
#: trade has to be able to say what closed it.
_EXIT_REASON: dict[str, str] = {
    "SELL_SIGNAL": "Score fell below the sell threshold",
    "MANUAL_CLOSE": "Closed by you from the Positions screen",
    # Named by reconciliation from the levels the trade carried, not submitted
    # by us — see `trade_manager._classify_bracket_exit`. Before that these two
    # were one value, `bracket_or_manual`, and the most basic question anyone
    # can ask of an exit record — did we hit targets or get stopped out — had no
    # answer in it.
    "TAKE_PROFIT": "Target reached — the take-profit leg filled",
    "STOP_LOSS": "Stopped out — the protective stop filled",
}

#: `EXIT_ALERT` is deliberately NOT here. It had a sentence for years and no
#: caller: `execute_exit`'s `trigger` defaulted to it and both call sites passed
#: something else, so this string could never be written. The setup scan's
#: overbought flag remains advisory — nothing sells on it — and a reason string
#: for an exit that cannot happen is the same class of lie as a gate panel that
#: contradicts the badge beside it. If that exit is ever wired, add it back with
#: the code that writes it.

#: Short phrases for the fill notification, which is a line rather than a
#: sentence. Separate from `_EXIT_REASON` because a push notification reads
#: "closed — target reached", not "Closed — Target reached — the take-profit
#: leg filled".
_TRIGGER_PHRASE: dict[str, str] = {
    "TAKE_PROFIT": "target reached",
    "STOP_LOSS": "stopped out",
    "SELL_SIGNAL": "sell signal",
    "MANUAL_CLOSE": "you closed it",
}


def exit_trigger_phrase(trigger: str | None) -> str | None:
    """A few words for a notification, or None when the trigger is unknown."""
    return _TRIGGER_PHRASE.get(trigger or "")


def exit_rationale(
    trigger: str,
    signal_score: float | None,
    *,
    feat: dict | None = None,
    user_weights: dict | None = None,
) -> str:
    """
    One sentence saying why this position is being sold.

    The drivers clause is added only for `SELL_SIGNAL`, and deliberately: that
    is the only exit the score decided. An exit alert came from the setup scan's
    own thresholds and a manual close came from a person, so decorating either
    with a factor decomposition would attribute the decision to arithmetic that
    had no part in it.
    """
    base = _EXIT_REASON.get(trigger, f"Closed on {trigger}")
    if trigger != "SELL_SIGNAL":
        return base

    if signal_score is not None:
        base = (
            f"{base} — scored {_pct(signal_score)}/100 against the "
            f"{_pct(SELL_THRESHOLD)} that triggers a sell"
        )
    drivers = _drivers_clause(feat, user_weights, favourable=False)
    # The base already spends its em dash on the score, so the drivers arrive
    # after a semicolon rather than a second dash in the same sentence.
    return base + drivers.replace(" — ", "; ", 1)
