import type { AnalyzeResponse } from '../types'

/**
 * Report export — plain text, email, and PDF.
 *
 * Lifted out of TickerPage when the 1.7 redesign replaced that page with the
 * Trade screen. The logic is unchanged: this is the same report the page has
 * exported since 1.4, and the PDF still carries the disclaimer footer.
 */

export function buildExportText(data: AnalyzeResponse): string {
  const lines: string[] = [
    `${data.ticker} — Analysis Report`,
    `Generated: ${new Date(data.generated_at).toLocaleString()}`,
    '',
    `Signal: ${data.signal}  |  Score: ${Math.round(data.score * 100)}/100  |  Confidence: ${Math.round(data.confidence * 100)}%`,
    data.conviction ? `Conviction: ${data.conviction}` : '',
    data.price_target ? `Price Target: $${data.price_target.toFixed(2)}` : '',
    data.stop_loss ? `Stop Loss: $${data.stop_loss.toFixed(2)}` : '',
    data.time_horizon ? `Time Horizon: ${data.time_horizon}` : '',
    '',
  ]

  if (data.thesis) lines.push('INVESTMENT THESIS', data.thesis, '')
  if (data.analyst_note) lines.push('ANALYST NOTE', data.analyst_note, '')
  if (data.bull_case) lines.push('BULL CASE', data.bull_case, '')
  if (data.bear_case) lines.push('BEAR CASE', data.bear_case, '')
  if (data.entry_suggestion) lines.push('ENTRY', data.entry_suggestion, '')
  if (data.exit_suggestion) lines.push('EXIT', data.exit_suggestion, '')
  if (data.catalysts?.length) lines.push('CATALYSTS', ...data.catalysts.map((c) => `• ${c}`), '')
  if (data.key_risks?.length) lines.push('KEY RISKS', ...data.key_risks.map((r) => `• ${r}`), '')
  if (data.explanation) lines.push('EXPLANATION', data.explanation, '')

  lines.push('---', 'Disclaimer: This report is generated by SAMSTradingAgent for informational purposes only and does not constitute financial advice.')
  return lines.filter((l) => l !== undefined).join('\n')
}

export function downloadTxt(data: AnalyzeResponse) {
  const text = buildExportText(data)
  const blob = new Blob([text], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${data.ticker}-analysis-${new Date().toISOString().slice(0, 10)}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

export function emailReport(data: AnalyzeResponse) {
  const subject = encodeURIComponent(`${data.ticker} Analysis — ${data.signal} (${Math.round(data.score * 100)}/100)`)
  const body = encodeURIComponent(buildExportText(data))
  window.location.href = `mailto:?subject=${subject}&body=${body}`
}

export async function downloadPdf(data: AnalyzeResponse) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'letter' })
  const margin = 48
  const pageW = doc.internal.pageSize.getWidth()
  const contentW = pageW - margin * 2
  let y = margin

  const brand = [242, 96, 12] as const  // #f2600c

  const addPage = () => {
    doc.addPage()
    y = margin
  }

  const checkY = (needed = 20) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) addPage()
  }

  const heading = (text: string, size = 10) => {
    checkY(20)
    doc.setFontSize(size)
    doc.setTextColor(...brand)
    doc.setFont('helvetica', 'bold')
    doc.text(text.toUpperCase(), margin, y)
    y += size + 4
    doc.setTextColor(30, 30, 30)
  }

  const body = (text: string, size = 9) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(60, 60, 60)
    const lines = doc.splitTextToSize(text, contentW) as string[]
    lines.forEach((line: string) => {
      checkY(size + 3)
      doc.text(line, margin, y)
      y += size + 3
    })
  }

  const divider = () => {
    checkY(12)
    doc.setDrawColor(220, 220, 220)
    doc.line(margin, y, pageW - margin, y)
    y += 10
  }

  const gap = (n = 12) => { y += n }

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...brand)
  doc.text(data.ticker, margin, y)

  if (data.current_price != null) {
    doc.setFontSize(14)
    doc.setTextColor(30, 30, 30)
    const priceStr = `$${data.current_price.toFixed(2)}${data.day_change_pct != null ? `  ${data.day_change_pct >= 0 ? '+' : ''}${data.day_change_pct.toFixed(2)}%` : ''}`
    doc.text(priceStr, margin, y + 22)
  }

  // Signal pill (right-aligned)
  const signalColor: Record<string, [number, number, number]> = {
    BUY: [34, 197, 94], SELL: [239, 68, 68], HOLD: [234, 179, 8],
  }
  const sc = signalColor[data.signal] ?? ([100, 100, 100] as [number, number, number])
  doc.setFillColor(...sc)
  doc.roundedRect(pageW - margin - 56, y - 16, 56, 22, 4, 4, 'F')
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text(data.signal, pageW - margin - 28, y - 1, { align: 'center' })

  y += 40
  divider()

  // ── Key metrics ───────────────────────────────────────────────────────────
  const score = Math.round(data.score * 100)
  const conf  = Math.round(data.confidence * 100)
  const metrics = [
    ['Score', `${score}/100`],
    ['Confidence', `${conf}%`],
    data.conviction ? ['Conviction', data.conviction] : null,
    data.price_target ? ['Price Target', `$${data.price_target.toFixed(2)}`] : null,
    data.stop_loss    ? ['Stop Loss',    `$${data.stop_loss.toFixed(2)}`]    : null,
    data.time_horizon ? ['Time Horizon', data.time_horizon]                  : null,
  ].filter(Boolean) as [string, string][]

  const colW = contentW / 3
  metrics.forEach(([label, value], i) => {
    const col = i % 3
    const row = Math.floor(i / 3)
    const cx = margin + col * colW
    const cy = y + row * 36
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(120, 120, 120)
    doc.text(label.toUpperCase(), cx, cy)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 30, 30)
    doc.text(value, cx, cy + 13)
  })

  y += Math.ceil(metrics.length / 3) * 36 + 4
  divider()

  // ── Sections ──────────────────────────────────────────────────────────────
  const section = (label: string, text?: string | null, items?: string[] | null) => {
    if (!text && !items?.length) return
    heading(label)
    if (text) body(text)
    if (items?.length) items.forEach((s) => body(`• ${s}`))
    gap(10)
  }

  section('Investment Thesis', data.thesis)
  section('Analyst Note', data.analyst_note)
  section('Bull Case', data.bull_case)
  section('Bear Case', data.bear_case)
  section('Catalysts', null, data.catalysts)
  section('Key Risks', null, data.key_risks)
  section('Entry', data.entry_suggestion)
  section('Exit', data.exit_suggestion)
  section('Explanation', data.explanation)

  // ── Footer ────────────────────────────────────────────────────────────────
  divider()
  doc.setFontSize(7)
  doc.setFont('helvetica', 'italic')
  doc.setTextColor(160, 160, 160)
  doc.text(
    `Generated ${new Date(data.generated_at).toLocaleString()}  ·  SAMSTradingAgent  ·  For informational purposes only, not financial advice.`,
    margin, y,
  )

  doc.save(`${data.ticker}-analysis-${new Date().toISOString().slice(0, 10)}.pdf`)
}

